--- 
title: "Data Wrangling with R"
author: "Bradley Boehmke"
site: bookdown::bookdown_site
output: bookdown::gitbook
documentclass: book
bibliography: references.bib
biblio-style: apalike
link-citations: yes
github-repo: bradleyboehmke/uc-bana-7025
twitter-handle: bradleyboehmke
description: "Master the art of data wrangling with the R programming language."
---

`r if (knitr::is_latex_output()) '<!--'` 

# Syllabus {-}

```{block, type = "note"}
This repository contains additional resources for the UC BANA 7025 Data Wrangling course. The following is a truncated syllabus; for the full syllabus along with complete course content please visit the online course content in [Canvas](https://uc.instructure.com/). 
```

Welcome to ___Data Wrangling with R___! This course provides an intensive, hands-on introduction to Data Wrangling with the R programming language. You will learn the fundamental skills required to acquire, munge, transform, manipulate, and visualize data in a computing environment that fosters reproducibility.

Data wrangling, which is also commonly referred to as data munging, transformation, manipulation, janitor work, etc. can be a painstakingly laborious process. In fact, it has been stated that up to 80% of data analysis is spent on the process of cleaning and preparing data [@tidy-data; @dasu2003exploratory]. However, being a prerequisite to the rest of the data analysis workflow (visualization, modeling, reporting), it's essential that you become fluent *and* efficient in data wrangling techniques.

## Learning Objectives {-}

This course will guide you through the data wrangling process along with give you a solid foundation of the basics of working with data in R. My goal is to teach you how to easily wrangle your data so you can spend more time focused on understanding the content of your data via visualization, modeling, and reporting your results. Upon successfully completing this course, you will be able to:

* Perform your data analysis in a literate programming environment
* Manage different types of data
* Manage different data structures
* Import and export data
* Index, subset, reshape and transform your data
* Compute descriptive statistics
* Visualize data
* Make your code efficient by using control statements & iteration
* Write your own functions

...all with R!

```{block, type = "note"}
This course assumes no prior knowledge of R. Experience with programming concepts or another programming language will help, but is not required to understand the material. 
```

## Material {-}

The bulk of the classroom material will be provided via this book, the recorded lectures, and class notes. In some cases there are additional recommended readings, all of which are readily available online.

## Class Structure {-}

__Modules__: For this class each module is covered over the course of week. In the "Overview" section for each module you will find overall learning objectives, a short description of the learning content covered in that module, along with all tasks that are required of you for that module (i.e. quizzes, lab). Each module will have two or more primary lessons and associated quizzes along with a lab.

__Lessons__: For each lesson you will read and work through the tutorial. Short videos will be sprinkled throughout the lesson to further discuss and reinforce lesson concepts. Each lesson will have various "Your Turn" exercises throughout, along with end-of-lesson exercises. I highly recommend you work through these exercises as they will prepare you for the quizzes, labs, and project work.

__Quizzes__: There will be a short quiz associated with _each lesson_. These quizzes will be hosted in the course website on Canvas. Please check Canvas for due dates for these quizzes.

__Labs__: There will be a lab associated with _each module_. For these labs students will be guided through a case study step-by-step. The aim is to provide a detailed view on how to manage a variety of complex real-world data; how to convert real problems into data wrangling and analysis problems; and to apply R to address these problems and extract insights from the data. Submission of these labs will be done through the course website on Canvas. Please check Canvas for due dates for these labs.

__Project__: TBD


## Schedule {-}

```{block, type = "note"}
See the [Canvas](https://uc.instructure.com/) course webpage for a detailed schedule with due dates for quizzes, labs, etc.
```

| Module        | Description                                         |
|:-------------:|:----------------------------------------------------|
| **1**         | **Introduction**                                    |
|               | Intro to data wrangling, R, and this course         |
|               | R fundamentals & the Rstudio IDE                    |
| **2**         | **Reproducible Documents and Importing Data**       |
|               | Managing your workflow and reproducibility          |
|               | Importing data and understanding the basics of it   |
| **3**         | **Tidy Data and Data Manipulation**                 |
|               | Tidying & preparing data for analysis               |
|               | Data manipulation                                   |
| **4**         | **Relational Data and More Tidyverse Packages**     |
|               | Relational data                                     |
|               | Leveraging the Tidyverse to simplify data wrangling |
| **5**         | **Data Visualization & Exploration**                |
|               | Data visualization                                  |
|               | Exploratory data analysis                           |
| **6**         | **Creating Efficient Code in R**                    |
|               | Control statements & iteration                      |
|               | Writing functions                                   |
| **7**         | **Introduction to Applied Modeling**                |
|               | Correlation & pattern discovery                     |
|               | Introduction to machine learning                    |

## Conventions used in this book {-}

The following typographical conventions are used in this book:

* ___strong italic___: indicates new terms,
* __bold__: indicates package & file names,
* `inline code`: monospaced highlighted text indicates functions or other commands that could be typed literally by the user,
* code chunk: indicates commands or other text that could be typed literally by the user

```{r, first-code-chunk, collapse=TRUE}
1 + 2
```

In addition to the general text used throughout, you will notice the following code chunks with images:

```{block, type = "tip"}
Signifies a tip or suggestion
```

```{block, type = "note"}
Signifies a general note
```

```{block, type = "warning"}
Signifies a warning or caution
```

## Feedback {-}

To report errors or bugs that you find in this course material please post an issue at https://github.com/bradleyboehmke/uc-bana-7025/issues. For all other communication be sure to use Canvas or the university email. 

```{block, type = "tip"}
When communicating with me via email, please always include **BANA7025** in the subject line.
```

## Acknowledgements {-}

This course and its materials have been influenced by the following resources:

- Jenny Bryan, [STAT 545: Data wrangling, exploration, and analysis with R](http://stat545.com/)
- Garrett Grolemund & Hadley Wickham, [R for Data Science](http://r4ds.had.co.nz/index.html)
- Stephanie Hicks, [Statistical Computing](https://www.stephaniehicks.com/jhustatcomputing2021/)
- Chester Ismay & Albert Kim, [ModernDive](https://moderndive.netlify.app/index.html)
