# (PART) Module 5 {-}

# Overview

Being able to create visualizations (graphical representations) of data is a key step in data analysis. In this module you will learn to use the **ggplot2** library to create the meaningful, elegant, and finely tuned data visualizations. You will also learn to combine data transformation, manipulation, and visualization to explore your data and start extracting key insights. During this process you take a slight detour to learn about factors and how to manipulate factors to improve your visualizations.

## Learning objectives

By the end of this module you should be able to:

- Build meaningful visualizations with **ggplot2**.
- Identify which plots to use to explore different types of variables.
- Combine descriptive statistics and visualization to identify summaries, relationships, differences, and abnormalities in the data. 
- Create and modify factor variables.

## Estimated time requirement

The estimated time to go through the module lessons is about:

* Reading only: 4 hours
* Reading + videos: 5 hours

## Tasks

```{block, type='todo'}
* Work through the 3 module lessons.
* Upon finishing each lesson take the associated lesson quizzes on Canvas. Be sure to complete the lesson quiz no later than the due date listed on Canvas.
* Check Canvas for this week's lab, lab quiz due date, and any additional content (i.e. in-class material)
```
